*** Starting uWSGI 2.0.15 (32bit) on [Tue Dec 19 01:21:08 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x9c3fd40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x9c3fd40 pid: 3087 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3087)
spawned uWSGI worker 1 (pid: 3089, cores: 2)
spawned uWSGI worker 2 (pid: 3090, cores: 2)
spawned uWSGI worker 3 (pid: 3091, cores: 2)
spawned uWSGI worker 4 (pid: 3092, cores: 2)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (32bit) on [Tue Dec 19 01:24:30 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x9e42d10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x9e42d10 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 3104, cores: 2)
spawned uWSGI worker 2 (pid: 3105, cores: 2)
spawned uWSGI worker 3 (pid: 3106, cores: 2)
spawned uWSGI worker 4 (pid: 3107, cores: 2)
[pid: 3106|app: 0|req: 1/1] 218.75.75.210 () {44 vars in 836 bytes} [Tue Dec 19 14:24:52 2017] GET / => generated 3151 bytes in 70 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3106|app: 0|req: 2/2] 218.75.75.210 () {46 vars in 838 bytes} [Tue Dec 19 14:24:53 2017] GET /favicon.ico => generated 3151 bytes in 21 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3104)...
Gracefully killing worker 2 (pid: 3105)...
Gracefully killing worker 3 (pid: 3106)...
Gracefully killing worker 4 (pid: 3107)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Tue Dec 19 14:25:03 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x98be488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x98be488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 3115, cores: 2)
spawned uWSGI worker 2 (pid: 3116, cores: 2)
spawned uWSGI worker 3 (pid: 3117, cores: 2)
spawned uWSGI worker 4 (pid: 3118, cores: 2)
[pid: 3116|app: 0|req: 1/1] 218.75.75.210 () {44 vars in 836 bytes} [Tue Dec 19 14:25:05 2017] GET / => generated 3151 bytes in 66 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3116|app: 0|req: 2/2] 218.75.75.210 () {46 vars in 838 bytes} [Tue Dec 19 14:25:05 2017] GET /favicon.ico => generated 3151 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 1/3] 218.75.75.210 () {44 vars in 860 bytes} [Tue Dec 19 14:39:51 2017] GET /reg.html => generated 5322 bytes in 77 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 2/4] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:39:51 2017] GET /check_code/ => generated 1740 bytes in 39 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 3/5] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:39:52 2017] GET /favicon.ico => generated 3151 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 4/6] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:17 2017] POST /reg.html => generated 5492 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 5/7] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:17 2017] GET /check_code/ => generated 1736 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 6/8] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:18 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 7/9] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:26 2017] POST /reg.html => generated 5492 bytes in 28 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 8/10] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:26 2017] GET /check_code/ => generated 1787 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 9/11] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:26 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 10/12] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:27 2017] POST /reg.html => generated 5492 bytes in 41 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 11/13] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:27 2017] GET /check_code/ => generated 1686 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 12/14] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:28 2017] GET /favicon.ico => generated 3151 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 13/15] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:28 2017] POST /reg.html => generated 5492 bytes in 33 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 14/16] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:28 2017] GET /check_code/ => generated 1661 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 15/17] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:29 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 16/18] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:29 2017] POST /reg.html => generated 5492 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 17/19] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:29 2017] GET /check_code/ => generated 1584 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 18/20] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:30 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 19/21] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:37 2017] POST /reg.html => generated 5492 bytes in 33 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 20/22] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:37 2017] GET /check_code/ => generated 1560 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 21/23] 218.75.75.210 () {46 vars in 846 bytes} [Tue Dec 19 14:40:37 2017] GET /favicon.ico => generated 3151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 22/24] 218.75.75.210 () {42 vars in 805 bytes} [Tue Dec 19 14:40:49 2017] GET / => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 23/25] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:40:50 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 24/26] 218.75.75.210 () {44 vars in 860 bytes} [Tue Dec 19 14:40:51 2017] GET /reg.html => generated 5322 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 25/27] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:51 2017] GET /check_code/ => generated 1870 bytes in 14 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 26/28] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:51 2017] GET /favicon.ico => generated 3151 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 27/29] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:40:53 2017] POST /reg.html => generated 5492 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 28/30] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:54 2017] GET /check_code/ => generated 1614 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 29/31] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:40:54 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 30/32] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:41:09 2017] POST /reg.html => generated 5475 bytes in 40 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 31/33] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:41:09 2017] GET /check_code/ => generated 1943 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 32/34] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:41:09 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 33/35] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 14:41:25 2017] POST /reg.html => generated 5533 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 34/36] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:41:25 2017] GET /check_code/ => generated 1547 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 35/37] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:41:25 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 36/38] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:42:13 2017] GET /favicon.ico => generated 3151 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 37/39] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:42:16 2017] GET /favicon.ico => generated 3151 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 38/40] 218.75.75.210 () {44 vars in 860 bytes} [Tue Dec 19 14:42:16 2017] GET /reg.html => generated 5322 bytes in 40 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 39/41] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:42:16 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 40/42] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:42:17 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 41/43] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:42:17 2017] GET /favicon.ico => generated 3151 bytes in 23 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 42/44] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:42:22 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 43/45] 218.75.75.210 () {44 vars in 864 bytes} [Tue Dec 19 14:42:24 2017] GET /login.html => generated 2923 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 44/46] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:42:24 2017] GET /check_code/ => generated 2028 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 45/47] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:42:24 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 46/48] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:42:34 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 47/49] 218.75.75.210 () {44 vars in 856 bytes} [Tue Dec 19 14:43:26 2017] GET /all/3/ => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 48/50] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:26 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 49/51] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:27 2017] GET /all/4/ => generated 3151 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 50/52] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:27 2017] GET /favicon.ico => generated 3151 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 51/53] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:28 2017] GET /all/2/ => generated 3151 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 52/54] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:29 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 53/55] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:29 2017] GET /all/1/ => generated 3151 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 54/56] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:29 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 55/57] 218.75.75.210 () {44 vars in 850 bytes} [Tue Dec 19 14:43:30 2017] GET / => generated 3151 bytes in 33 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 56/58] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:43:30 2017] GET /favicon.ico => generated 3151 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 57/59] 218.75.75.210 () {44 vars in 856 bytes} [Tue Dec 19 14:43:30 2017] GET /all/1/ => generated 3151 bytes in 21 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 58/60] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:31 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 59/61] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:31 2017] GET /all/2/ => generated 3151 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 60/62] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:31 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 61/63] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:32 2017] GET /all/3/ => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 62/64] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:32 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 63/65] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:32 2017] GET /all/4/ => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 64/66] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:33 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 65/67] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:35 2017] GET /all/3/ => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 66/68] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:35 2017] GET /favicon.ico => generated 3151 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 67/69] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:36 2017] GET /all/2/ => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 68/70] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:36 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 69/71] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:36 2017] GET /all/1/ => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 70/72] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:37 2017] GET /favicon.ico => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 71/73] 218.75.75.210 () {44 vars in 850 bytes} [Tue Dec 19 14:43:37 2017] GET / => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 72/74] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:43:38 2017] GET /favicon.ico => generated 3151 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 73/75] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:43:38 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 74/76] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:43:41 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 75/77] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 14:43:42 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 76/78] 218.75.75.210 () {44 vars in 856 bytes} [Tue Dec 19 14:43:43 2017] GET /all/4/ => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 77/79] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:43 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 78/80] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:43 2017] GET /all/3/ => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 79/81] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:44 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 80/82] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:43:44 2017] GET /all/2/ => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 81/83] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:43:45 2017] GET /favicon.ico => generated 3151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 82/84] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:49:56 2017] GET /all/3/ => generated 3151 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 83/85] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:49:56 2017] GET /favicon.ico => generated 3151 bytes in 35 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 84/86] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:49:57 2017] GET /all/4/ => generated 3151 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 85/87] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:49:57 2017] GET /favicon.ico => generated 3151 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 86/88] 218.75.75.210 () {44 vars in 866 bytes} [Tue Dec 19 14:50:04 2017] GET /reg.html => generated 5322 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 87/89] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:50:04 2017] GET /check_code/ => generated 1398 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 88/90] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:50:04 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 89/91] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:05 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 90/92] 218.75.75.210 () {44 vars in 870 bytes} [Tue Dec 19 14:50:06 2017] GET /login.html => generated 2923 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 91/93] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:50:07 2017] GET /check_code/ => generated 1766 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 92/94] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:50:07 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 93/95] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:08 2017] GET /favicon.ico => generated 3151 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 94/96] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:50:18 2017] GET /all/1/ => generated 3151 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 95/97] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:19 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 96/98] 218.75.75.210 () {44 vars in 862 bytes} [Tue Dec 19 14:50:19 2017] GET /all/2/ => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 97/99] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:19 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 98/100] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:20 2017] GET /favicon.ico => generated 3151 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 99/101] 218.75.75.210 () {44 vars in 866 bytes} [Tue Dec 19 14:50:21 2017] GET /reg.html => generated 5322 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 100/102] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:50:22 2017] GET /check_code/ => generated 1642 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 101/103] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 14:50:22 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 102/104] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:24 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 103/105] 218.75.75.210 () {44 vars in 870 bytes} [Tue Dec 19 14:50:25 2017] GET /login.html => generated 2923 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 104/106] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:50:25 2017] GET /check_code/ => generated 1847 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 105/107] 218.75.75.210 () {42 vars in 795 bytes} [Tue Dec 19 14:50:25 2017] GET /favicon.ico => generated 3151 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 106/108] 218.75.75.210 () {42 vars in 791 bytes} [Tue Dec 19 14:50:26 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 107/109] 218.75.75.210 () {42 vars in 805 bytes} [Tue Dec 19 15:15:16 2017] GET / => generated 3151 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 108/110] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 15:15:16 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 109/111] 218.75.75.210 () {44 vars in 860 bytes} [Tue Dec 19 15:15:27 2017] GET /reg.html => generated 5322 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 110/112] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:15:27 2017] GET /check_code/ => generated 1634 bytes in 20 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 111/113] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:15:27 2017] GET /favicon.ico => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 112/114] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:16:50 2017] POST /up_img/ => generated 20 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
Internal Server Error: /reg.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./app01/views.py", line 108, in reg
    models.UserInfo.objects.create(**obj.cleaned_data)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 415, in create
    obj = self.model(**kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/base.py", line 495, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'code' is an invalid keyword argument for this function
[pid: 3118|app: 0|req: 1/115] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:16:56 2017] POST /reg.html => generated 74306 bytes in 261 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 3118|app: 0|req: 2/116] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:16:57 2017] GET /favicon.ico => generated 3151 bytes in 31 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 113/117] 218.75.75.210 () {42 vars in 805 bytes} [Tue Dec 19 15:56:10 2017] GET / => generated 3151 bytes in 23 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 114/118] 218.75.75.210 () {42 vars in 785 bytes} [Tue Dec 19 15:56:10 2017] GET /favicon.ico => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 115/119] 218.75.75.210 () {44 vars in 860 bytes} [Tue Dec 19 15:56:12 2017] GET /reg.html => generated 5322 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 116/120] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:56:12 2017] GET /check_code/ => generated 1734 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 117/121] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:56:12 2017] GET /favicon.ico => generated 3151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 118/122] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:56:48 2017] POST /up_img/ => generated 20 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 3118|app: 0|req: 3/123] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:56:55 2017] POST /reg.html => generated 5480 bytes in 34 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3118|app: 0|req: 4/124] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:56:55 2017] GET /check_code/ => generated 1782 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 119/125] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:56:55 2017] GET /favicon.ico => generated 3151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 120/126] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:58:41 2017] POST /up_img/ => generated 20 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 121/127] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:58:42 2017] POST /reg.html => generated 5470 bytes in 71 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 122/128] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:58:43 2017] GET /check_code/ => generated 1815 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 3115|app: 0|req: 123/129] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:58:43 2017] GET /favicon.ico => generated 3151 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 124/130] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:58:52 2017] POST /up_img/ => generated 20 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
Internal Server Error: /reg.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./app01/views.py", line 108, in reg
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 415, in create
    obj = self.model(**kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/base.py", line 495, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'code' is an invalid keyword argument for this function
[pid: 3116|app: 0|req: 3/131] 218.75.75.210 () {52 vars in 1123 bytes} [Tue Dec 19 15:58:56 2017] POST /reg.html => generated 71733 bytes in 157 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 3115|app: 0|req: 125/132] 218.75.75.210 () {42 vars in 793 bytes} [Tue Dec 19 15:58:57 2017] GET /favicon.ico => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3115)...
Gracefully killing worker 2 (pid: 3116)...
Gracefully killing worker 3 (pid: 3117)...
Gracefully killing worker 4 (pid: 3118)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Tue Dec 19 17:13:51 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x9181488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9181488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 3425, cores: 2)
spawned uWSGI worker 2 (pid: 3426, cores: 2)
spawned uWSGI worker 3 (pid: 3427, cores: 2)
spawned uWSGI worker 4 (pid: 3428, cores: 2)
Internal Server Error: /all/4/
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
Internal Server Error: /all/2/
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 2/1] 115.239.138.180 () {34 vars in 485 bytes} [Tue Dec 19 18:00:35 2017] GET /all/2/ => generated 97742 bytes in 277 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
[pid: 3425|app: 0|req: 2/2] 115.239.138.180 () {34 vars in 485 bytes} [Tue Dec 19 18:00:35 2017] GET /all/4/ => generated 97742 bytes in 297 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /login.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3427|app: 0|req: 1/3] 115.239.138.180 () {34 vars in 493 bytes} [Tue Dec 19 18:00:35 2017] GET /login.html => generated 112882 bytes in 176 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /all/1/
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 3/4] 115.239.138.180 () {34 vars in 485 bytes} [Tue Dec 19 18:00:36 2017] GET /all/1/ => generated 97742 bytes in 103 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /reg.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3427|app: 0|req: 2/5] 115.239.138.180 () {34 vars in 489 bytes} [Tue Dec 19 18:00:56 2017] GET /reg.html => generated 112848 bytes in 104 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
[pid: 3425|app: 0|req: 4/6] 155.94.88.18 () {30 vars in 371 bytes} [Tue Dec 19 18:07:37 2017] GET / => generated 53638 bytes in 65 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Internal Server Error: /all/3/
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 5/7] 115.239.138.180 () {34 vars in 485 bytes} [Tue Dec 19 18:13:32 2017] GET /all/3/ => generated 97742 bytes in 95 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
[pid: 3425|app: 0|req: 6/8] 84.86.241.203 () {28 vars in 312 bytes} [Tue Dec 19 18:30:20 2017] GET / => generated 53475 bytes in 60 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Internal Server Error: /manager/html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 7/9] 187.75.224.11 () {38 vars in 547 bytes} [Tue Dec 19 22:11:05 2017] GET /manager/html => generated 113160 bytes in 132 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
[pid: 3425|app: 0|req: 8/10] 123.151.42.61 () {36 vars in 420 bytes} [Tue Dec 19 23:34:49 2017] GET / => generated 54057 bytes in 71 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 9/11] 60.191.38.77 () {36 vars in 574 bytes} [Wed Dec 20 02:07:05 2017] GET / => generated 97875 bytes in 159 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
[pid: 3425|app: 0|req: 10/12] 5.188.87.7 () {30 vars in 322 bytes} [Wed Dec 20 04:04:38 2017] GET / => generated 53589 bytes in 62 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 11/13] 222.186.138.64 () {34 vars in 450 bytes} [Wed Dec 20 05:01:12 2017] GET / => generated 97641 bytes in 94 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /index.action
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 12/14] 222.186.138.64 () {34 vars in 2193 bytes} [Wed Dec 20 05:01:13 2017] GET /index.action => generated 114848 bytes in 91 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /muieblackcat
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 13/15] 46.246.39.69 () {36 vars in 436 bytes} [Wed Dec 20 05:13:07 2017] GET /muieblackcat => generated 112945 bytes in 130 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 1)
Internal Server Error: /phpMyAdmin/scripts/setup.php
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 14/16] 46.246.39.69 () {36 vars in 469 bytes} [Wed Dec 20 05:13:07 2017] GET //phpMyAdmin/scripts/setup.php => generated 113218 bytes in 112 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
[pid: 3425|app: 0|req: 15/17] 24.37.148.250 () {26 vars in 277 bytes} [Wed Dec 20 08:43:07 2017] GET / => generated 53336 bytes in 78 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 16/18] 209.126.136.4 () {32 vars in 467 bytes} [Wed Dec 20 10:23:41 2017] GET / => generated 97554 bytes in 110 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /reg.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 17/19] 218.75.75.210 () {42 vars in 821 bytes} [Wed Dec 20 10:51:30 2017] GET /reg.html => generated 114118 bytes in 115 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 1)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 18/20] 218.75.75.210 () {42 vars in 793 bytes} [Wed Dec 20 10:51:31 2017] GET /favicon.ico => generated 114135 bytes in 127 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 19/21] 218.75.75.210 () {42 vars in 805 bytes} [Wed Dec 20 10:57:05 2017] GET / => generated 99117 bytes in 137 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 60, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/middleware/common.py", line 78, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 155, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 3425|app: 0|req: 20/22] 218.75.75.210 () {42 vars in 785 bytes} [Wed Dec 20 10:57:06 2017] GET /favicon.ico => generated 114127 bytes in 141 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3425)...
Gracefully killing worker 2 (pid: 3426)...
Gracefully killing worker 3 (pid: 3427)...
Gracefully killing worker 4 (pid: 3428)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Wed Dec 20 10:58:53 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x8a2b488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8a2b488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 4332, cores: 2)
spawned uWSGI worker 2 (pid: 4333, cores: 2)
spawned uWSGI worker 3 (pid: 4334, cores: 2)
spawned uWSGI worker 4 (pid: 4335, cores: 2)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 4332|app: 0|req: 1/1] 218.75.75.210 () {48 vars in 927 bytes} [Wed Dec 20 11:05:09 2017] GET / => generated 99561 bytes in 211 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.weibn.me'. You may need to add 'www.weibn.me' to ALLOWED_HOSTS.
[pid: 4332|app: 0|req: 2/2] 218.75.75.210 () {46 vars in 791 bytes} [Wed Dec 20 11:19:45 2017] GET / => generated 54956 bytes in 64 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 4332|app: 0|req: 3/3] 164.52.0.141 () {38 vars in 592 bytes} [Wed Dec 20 11:20:41 2017] GET / => generated 97983 bytes in 131 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.weibn.me'. You may need to add 'www.weibn.me' to ALLOWED_HOSTS.
[pid: 4332|app: 0|req: 4/4] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:23:14 2017] GET / => generated 54647 bytes in 50 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.weibn.me'. You may need to add 'www.weibn.me' to ALLOWED_HOSTS.
[pid: 4332|app: 0|req: 5/5] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:23:18 2017] GET / => generated 54647 bytes in 60 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 4333)...
Gracefully killing worker 3 (pid: 4334)...
Gracefully killing worker 4 (pid: 4335)...
Gracefully killing worker 1 (pid: 4332)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Wed Dec 20 11:23:42 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x83d6488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x83d6488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 4475, cores: 2)
spawned uWSGI worker 2 (pid: 4476, cores: 2)
spawned uWSGI worker 3 (pid: 4477, cores: 2)
spawned uWSGI worker 4 (pid: 4478, cores: 2)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 107
    return render(request,'sign.html',{'msg':'验证码错误','obj':obj}
         ^
IndentationError: expected an indented block
[pid: 4476|app: 0|req: 1/1] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:23:46 2017] GET / => generated 98287 bytes in 145 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 109
    if not obj.is_valid():
                         ^
SyntaxError: invalid syntax
[pid: 4476|app: 0|req: 2/2] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:38:12 2017] GET / => generated 98128 bytes in 95 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 109
    if not obj.is_valid():
                         ^
SyntaxError: invalid syntax
[pid: 4475|app: 0|req: 1/3] 218.75.75.210 () {40 vars in 669 bytes} [Wed Dec 20 11:38:56 2017] GET / => generated 97993 bytes in 153 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 109
    if not obj.is_valid():
                         ^
SyntaxError: invalid syntax
[pid: 4475|app: 0|req: 2/4] 218.75.75.210 () {40 vars in 669 bytes} [Wed Dec 20 11:38:57 2017] GET / => generated 97993 bytes in 98 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 109
    if not obj.is_valid():
                         ^
SyntaxError: invalid syntax
[pid: 4475|app: 0|req: 3/5] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:42:07 2017] GET / => generated 98130 bytes in 117 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./blogtest/urls.py", line 18, in <module>
    from app01 import views
  File "./app01/views.py", line 109
    if not obj.is_valid():
                         ^
SyntaxError: invalid syntax
[pid: 4475|app: 0|req: 4/6] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:48:37 2017] GET / => generated 98130 bytes in 102 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 5/7] 218.75.75.210 () {42 vars in 700 bytes} [Wed Dec 20 11:53:08 2017] GET / => generated 3151 bytes in 63 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 6/8] 218.75.75.210 () {42 vars in 721 bytes} [Wed Dec 20 11:53:29 2017] GET /reg.html => generated 5322 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 7/9] 218.75.75.210 () {42 vars in 743 bytes} [Wed Dec 20 11:53:29 2017] GET /check_code/ => generated 1528 bytes in 25 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 8/10] 218.75.75.210 () {42 vars in 802 bytes} [Wed Dec 20 11:54:19 2017] GET / => generated 3151 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 9/11] 218.75.75.210 () {44 vars in 854 bytes} [Wed Dec 20 11:54:21 2017] GET /reg.html => generated 5322 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 10/12] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:54:54 2017] POST /up_img/ => generated 20 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 4478|app: 0|req: 1/13] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:54:59 2017] POST /reg.html => generated 0 bytes in 81 msecs (HTTP/1.1 302) 5 headers in 147 bytes (1 switches on core 0)
[pid: 4478|app: 0|req: 2/14] 218.75.75.210 () {46 vars in 897 bytes} [Wed Dec 20 11:54:59 2017] GET /login.html => generated 2923 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 11/15] 218.75.75.210 () {42 vars in 789 bytes} [Wed Dec 20 11:55:00 2017] GET /check_code/ => generated 1596 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 12/16] 218.75.75.210 () {52 vars in 1050 bytes} [Wed Dec 20 11:55:12 2017] POST /login.html => generated 2980 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 13/17] 218.75.75.210 () {42 vars in 789 bytes} [Wed Dec 20 11:55:12 2017] GET /check_code/ => generated 1612 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 14/18] 218.75.75.210 () {44 vars in 866 bytes} [Wed Dec 20 11:55:27 2017] GET /login.html => generated 2923 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 15/19] 218.75.75.210 () {44 vars in 854 bytes} [Wed Dec 20 11:55:28 2017] GET /reg.html => generated 5322 bytes in 28 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /up_img/
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./app01/views.py", line 205, in up_img
    file_path = ('static/img/' + file_obj.name)
AttributeError: 'NoneType' object has no attribute 'name'
[pid: 4475|app: 0|req: 16/20] 218.75.75.210 () {52 vars in 1112 bytes} [Wed Dec 20 11:56:06 2017] POST /up_img/ => generated 58824 bytes in 86 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 17/21] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:10 2017] POST /up_img/ => generated 20 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 4478|app: 0|req: 3/22] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:16 2017] POST /reg.html => generated 5511 bytes in 39 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 4478|app: 0|req: 4/23] 218.75.75.210 () {42 vars in 787 bytes} [Wed Dec 20 11:56:16 2017] GET /check_code/ => generated 1578 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 18/24] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:29 2017] POST /up_img/ => generated 20 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 4477|app: 0|req: 1/25] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:34 2017] POST /reg.html => generated 5490 bytes in 117 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 19/26] 218.75.75.210 () {42 vars in 787 bytes} [Wed Dec 20 11:56:34 2017] GET /check_code/ => generated 1407 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 1)
[pid: 4477|app: 0|req: 2/27] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:51 2017] POST /up_img/ => generated 20 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 20/28] 218.75.75.210 () {52 vars in 1114 bytes} [Wed Dec 20 11:56:57 2017] POST /reg.html => generated 0 bytes in 32 msecs (HTTP/1.1 302) 5 headers in 147 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 21/29] 218.75.75.210 () {46 vars in 897 bytes} [Wed Dec 20 11:56:57 2017] GET /login.html => generated 2923 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 22/30] 218.75.75.210 () {42 vars in 789 bytes} [Wed Dec 20 11:56:58 2017] GET /check_code/ => generated 1688 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 23/31] 218.75.75.210 () {52 vars in 1050 bytes} [Wed Dec 20 11:57:15 2017] POST /login.html => generated 2968 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 24/32] 218.75.75.210 () {42 vars in 789 bytes} [Wed Dec 20 11:57:16 2017] GET /check_code/ => generated 1826 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 255 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 25/33] 218.75.75.210 () {52 vars in 1050 bytes} [Wed Dec 20 11:57:20 2017] POST /login.html => generated 0 bytes in 18 msecs (HTTP/1.1 302) 6 headers in 268 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 26/34] 218.75.75.210 () {46 vars in 879 bytes} [Wed Dec 20 11:57:20 2017] GET / => generated 3327 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 27/35] 218.75.75.210 () {44 vars in 862 bytes} [Wed Dec 20 11:57:27 2017] GET /control.html => generated 1674 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 28/36] 218.75.75.210 () {44 vars in 850 bytes} [Wed Dec 20 11:57:50 2017] GET /all/1/ => generated 3327 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 29/37] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 11:57:50 2017] GET /all/2/ => generated 3327 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 30/38] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 11:57:51 2017] GET /all/3/ => generated 3327 bytes in 21 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 31/39] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 11:57:51 2017] GET /all/4/ => generated 3327 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 32/40] 218.75.75.210 () {44 vars in 868 bytes} [Wed Dec 20 11:57:52 2017] GET /control.html => generated 1674 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 33/41] 218.75.75.210 () {44 vars in 900 bytes} [Wed Dec 20 11:57:54 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 34 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 34/42] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:16 2017] GET /article_manage/4-0-0.html => generated 4165 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 35/43] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:18 2017] GET /article_manage/3-0-0.html => generated 4165 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 36/44] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:19 2017] GET /article_manage/2-0-0.html => generated 4165 bytes in 33 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 37/45] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:19 2017] GET /article_manage/1-0-0.html => generated 4165 bytes in 28 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 38/46] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:20 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 39/47] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:21 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 33 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 40/48] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:22 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 41/49] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:32 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 42/50] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 11:58:36 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 43/51] 218.75.75.210 () {44 vars in 873 bytes} [Wed Dec 20 11:58:39 2017] GET /.html => generated 3327 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 44/52] 218.75.75.210 () {44 vars in 867 bytes} [Wed Dec 20 11:58:41 2017] GET /control.html => generated 1674 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4475|app: 0|req: 45/53] 218.75.75.210 () {44 vars in 900 bytes} [Wed Dec 20 11:58:56 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 28 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4475|app: 0|req: 46/54] 218.75.75.210 () {44 vars in 895 bytes} [Wed Dec 20 11:59:02 2017] GET /add_article.html => generated 3086 bytes in 44 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /add_article.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./app01/views.py", line 375, in add_article
    print(obj.is_valid())
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/forms/forms.py", line 179, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/forms/forms.py", line 174, in errors
    self.full_clean()
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/forms/forms.py", line 376, in full_clean
    self._clean_fields()
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/forms/forms.py", line 397, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "./utils/FormInfo.py", line 148, in clean_content
    from utils.xss import xss
  File "./utils/xss.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
[pid: 4475|app: 0|req: 47/55] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 11:59:40 2017] POST /add_article.html => generated 87897 bytes in 111 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4475)...
Gracefully killing worker 2 (pid: 4476)...
Gracefully killing worker 3 (pid: 4477)...
Gracefully killing worker 4 (pid: 4478)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Wed Dec 20 13:11:46 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0xa1be488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xa1be488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 4616, cores: 2)
spawned uWSGI worker 2 (pid: 4617, cores: 2)
spawned uWSGI worker 3 (pid: 4618, cores: 2)
spawned uWSGI worker 4 (pid: 4619, cores: 2)
False
[pid: 4619|app: 0|req: 1/1] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:11:58 2017] POST /add_article.html => generated 3176 bytes in 200 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
False
[pid: 4619|app: 0|req: 2/2] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:04 2017] POST /add_article.html => generated 3176 bytes in 43 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 1/3] 218.75.75.210 () {42 vars in 802 bytes} [Wed Dec 20 13:12:22 2017] GET / => generated 3327 bytes in 64 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 2/4] 218.75.75.210 () {44 vars in 850 bytes} [Wed Dec 20 13:12:25 2017] GET /all/4/ => generated 3327 bytes in 19 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
False
[pid: 4616|app: 0|req: 3/5] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:33 2017] POST /add_article.html => generated 3176 bytes in 76 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
False
[pid: 4616|app: 0|req: 4/6] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:38 2017] POST /add_article.html => generated 3176 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
False
[pid: 4616|app: 0|req: 5/7] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:40 2017] POST /add_article.html => generated 3176 bytes in 39 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
False
[pid: 4616|app: 0|req: 6/8] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:43 2017] POST /add_article.html => generated 3176 bytes in 31 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 1)
False
[pid: 4616|app: 0|req: 7/9] 218.75.75.210 () {52 vars in 1068 bytes} [Wed Dec 20 13:12:45 2017] POST /add_article.html => generated 3176 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 8/10] 218.75.75.210 () {46 vars in 881 bytes} [Wed Dec 20 13:12:47 2017] GET /all/4/ => generated 3327 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 9/11] 218.75.75.210 () {46 vars in 881 bytes} [Wed Dec 20 13:12:48 2017] GET /all/4/ => generated 3327 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 10/12] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 13:12:49 2017] GET /all/4/ => generated 3327 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 11/13] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 13:12:49 2017] GET /all/3/ => generated 3327 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 12/14] 218.75.75.210 () {44 vars in 856 bytes} [Wed Dec 20 13:12:50 2017] GET /all/4/ => generated 3327 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 13/15] 218.75.75.210 () {42 vars in 812 bytes} [Wed Dec 20 13:13:29 2017] GET /user/ => generated 3327 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 14/16] 218.75.75.210 () {44 vars in 843 bytes} [Wed Dec 20 13:13:33 2017] GET /user/ => generated 3327 bytes in 21 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 15/17] 218.75.75.210 () {44 vars in 867 bytes} [Wed Dec 20 13:14:53 2017] GET /control.html => generated 1674 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 16/18] 218.75.75.210 () {44 vars in 900 bytes} [Wed Dec 20 13:15:03 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 17/19] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:15:05 2017] GET /article_manage/4-0-0.html => generated 4165 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 18/20] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:15:07 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 19/21] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:15:08 2017] GET /article_manage/4-0-0.html => generated 4165 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 20/22] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:15:09 2017] GET /article_manage/3-0-0.html => generated 4165 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 21/23] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:19:17 2017] GET /article_manage/1-0-0.html => generated 4165 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 22/24] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:19:18 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 23/25] 218.75.75.210 () {44 vars in 913 bytes} [Wed Dec 20 13:19:19 2017] GET /article_manage/2-0-0.html => generated 4165 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 24/26] 218.75.75.210 () {44 vars in 873 bytes} [Wed Dec 20 13:19:24 2017] GET /.html => generated 3327 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 25/27] 218.75.75.210 () {44 vars in 867 bytes} [Wed Dec 20 13:19:32 2017] GET /control.html => generated 1674 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4616|app: 0|req: 26/28] 218.75.75.210 () {44 vars in 900 bytes} [Wed Dec 20 13:19:53 2017] GET /article_manage/0-0-0.html => generated 4162 bytes in 23 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4616|app: 0|req: 27/29] 218.75.75.210 () {42 vars in 810 bytes} [Wed Dec 20 13:20:59 2017] GET /seek => generated 3327 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /seek.html
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1305, 'FUNCTION blog.strftime does not exist')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./app01/views.py", line 162, in user
    'cate_list':cate_list,'tags_list':tags_list,'page_info':page_info})
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 107, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1014, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python3.6/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1305, 'FUNCTION blog.strftime does not exist')
[pid: 4616|app: 0|req: 28/30] 218.75.75.210 () {42 vars in 820 bytes} [Wed Dec 20 13:21:06 2017] GET /seek.html => generated 244319 bytes in 316 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4616)...
Gracefully killing worker 2 (pid: 4617)...
Gracefully killing worker 3 (pid: 4618)...
Gracefully killing worker 4 (pid: 4619)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/beyond/blogtest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3.6/bin/uwsgi
[uWSGI] getting INI configuration from wsgi_http.ini
*** Starting uWSGI 2.0.15 (32bit) on [Wed Dec 20 14:43:23 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 15 December 2017 04:30:59
os: Linux-4.10.4-1.el6.elrepo.i686 #1 SMP Sat Mar 18 11:05:18 EDT 2017
nodename: host.localdomain
machine: i686
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/beyond/blogtest
detected binary path: /usr/local/python3.6/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/beyond/blogtest
your processes number limit is 3897
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
Python version: 3.6.3 (default, Dec 14 2017, 23:00:42)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Python main interpreter initialized at 0x970d488
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 357000 bytes (348 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x970d488 pid: 3102 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3102)
spawned uWSGI worker 1 (pid: 4717, cores: 2)
spawned uWSGI worker 2 (pid: 4718, cores: 2)
spawned uWSGI worker 3 (pid: 4719, cores: 2)
spawned uWSGI worker 4 (pid: 4720, cores: 2)
[pid: 4717|app: 0|req: 1/1] 218.75.75.210 () {42 vars in 802 bytes} [Wed Dec 20 14:48:23 2017] GET / => generated 3327 bytes in 86 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4717|app: 0|req: 2/2] 175.42.0.110 () {30 vars in 380 bytes} [Wed Dec 20 15:48:43 2017] GET /device_description.xml => generated 3151 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4717|app: 0|req: 3/3] 178.48.17.9 () {28 vars in 310 bytes} [Wed Dec 20 16:15:40 2017] GET / => generated 3151 bytes in 15 msecs (HTTP/1.0 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4717|app: 0|req: 4/4] 183.57.53.177 () {38 vars in 622 bytes} [Wed Dec 20 16:58:00 2017] GET / => generated 3151 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
[pid: 4717|app: 0|req: 5/5] 61.151.179.27 () {40 vars in 646 bytes} [Wed Dec 20 16:58:00 2017] GET / => generated 3151 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 4717|app: 0|req: 6/6] 61.151.178.180 () {38 vars in 587 bytes} [Wed Dec 20 16:58:59 2017] GET / => generated 3151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 1)
